#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : lv2
Version  : 1.18.2
Release  : 337
URL      : file:///aot/build/clearlinux/packages/lv2/lv2-v1.18.2.tar.gz
Source0  : file:///aot/build/clearlinux/packages/lv2/lv2-v1.18.2.tar.gz
Summary  : An extensible audio plugin interface.
Group    : Development/Tools
License  : GPL-2.0
Requires: lv2-bin = %{version}-%{release}
Requires: lv2-data = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-dev32
BuildRequires : autogen
BuildRequires : autogen-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : buildreq-distutils3
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : cairo-dev
BuildRequires : clr-rpm-config
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : fftw-dev
BuildRequires : findutils
BuildRequires : flac-dev
BuildRequires : flac-dev32
BuildRequires : flac-staticdev
BuildRequires : flac-staticdev32
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : glibc-staticdev
BuildRequires : gtk+-dev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libogg-dev
BuildRequires : libogg-dev32
BuildRequires : libogg-staticdev
BuildRequires : libogg-staticdev32
BuildRequires : libsndfile-dev
BuildRequires : libsndfile-staticdev
BuildRequires : libstdc++
BuildRequires : libtool-dev
BuildRequires : libvorbis-dev
BuildRequires : libvorbis-dev32
BuildRequires : libvorbis-staticdev
BuildRequires : libvorbis-staticdev32
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : ncurses-dev
BuildRequires : octave-dev
BuildRequires : opus
BuildRequires : opus-dev
BuildRequires : opus-lib
BuildRequires : opus-staticdev
BuildRequires : pcre-dev
BuildRequires : pcre-staticdev
BuildRequires : pcre2-dev
BuildRequires : pcre2-staticdev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pypi(html5lib)
BuildRequires : pypi(importlib_metadata)
BuildRequires : pypi(isodate)
BuildRequires : pypi(pyparsing)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : rdflib
BuildRequires : sed
BuildRequires : serd
BuildRequires : serd-dev
BuildRequires : serd-staticdev
BuildRequires : sord
BuildRequires : sord-dev
BuildRequires : sord-staticdev
BuildRequires : speex-dev
BuildRequires : speex-staticdev
BuildRequires : speexdsp-dev
BuildRequires : speexdsp-staticdev
BuildRequires : sqlite-autoconf-dev
BuildRequires : sqlite-autoconf-dev32
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : yaml-cpp
BuildRequires : yaml-cpp-dev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-PGO-Build.patch

%description
This directory contains third-party vocabularies used in these LV2
specifications.  They are occasionally very slightly modified for validity, but
are otherwise equivalent to their original versions.

%package bin
Summary: bin components for the lv2 package.
Group: Binaries
Requires: lv2-data = %{version}-%{release}

%description bin
bin components for the lv2 package.


%package data
Summary: data components for the lv2 package.
Group: Data

%description data
data components for the lv2 package.


%package dev
Summary: dev components for the lv2 package.
Group: Development
Requires: lv2-bin = %{version}-%{release}
Requires: lv2-data = %{version}-%{release}
Provides: lv2-devel = %{version}-%{release}
Requires: lv2 = %{version}-%{release}

%description dev
dev components for the lv2 package.


%prep
%setup -q -n lv2
cd %{_builddir}/lv2
%patch1 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639845969
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
unset ASFLAGS
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage -fprofile-partial-training -fprofile-correction -freorder-functions --coverage -lgcov"
export CFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export ASMFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export FCFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export FFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export CXXFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export LDFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export LIBS_GENERATE="-lgcov"
export PGO_USE="-Wmissing-profile -Wcoverage-mismatch -fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-partial-training -fprofile-correction -freorder-functions"
export CFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export ASMFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags_pgo end
if [ ! -f statuspgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
export ASMFLAGS="${ASMFLAGS_GENERATE}"
export LIBS="${LIBS_GENERATE}"
sd -r 'allow_unknown=False' 'allow_unknown=True' waflib/ || :
%waf --out=builddir  --no-coverage \
--test \
--copy-headers || :
./waf build --verbose --jobs=16 --out=builddir

## profile_payload start
unset LD_LIBRARY_PATH
unset LIBRARY_PATH
./waf -v test
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
## profile_payload end
./waf distclean --verbose || :
echo USED > statuspgo
fi
if [ -f statuspgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
export ASMFLAGS="${ASMFLAGS_USE}"
export LIBS="${LIBS_USE}"
sd -r 'allow_unknown=False' 'allow_unknown=True' waflib/ || :
%waf --out=builddir --no-coverage \
--test \
--copy-headers  || :
./waf build --verbose --jobs=16 --out=builddir
fi

%install
%waf_install -- --verbose

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lv2_validate
/usr/bin/lv2specgen.py

%files data
%defattr(-,root,root,-)
/usr/share/lv2specgen/DTD/xhtml-attribs-1.mod
/usr/share/lv2specgen/DTD/xhtml-base-1.mod
/usr/share/lv2specgen/DTD/xhtml-basic-table-1.mod
/usr/share/lv2specgen/DTD/xhtml-basic11-model-1.mod
/usr/share/lv2specgen/DTD/xhtml-basic11.dtd
/usr/share/lv2specgen/DTD/xhtml-bdo-1.mod
/usr/share/lv2specgen/DTD/xhtml-blkphras-1.mod
/usr/share/lv2specgen/DTD/xhtml-blkpres-1.mod
/usr/share/lv2specgen/DTD/xhtml-blkstruct-1.mod
/usr/share/lv2specgen/DTD/xhtml-charent-1.mod
/usr/share/lv2specgen/DTD/xhtml-csismap-1.mod
/usr/share/lv2specgen/DTD/xhtml-datatypes-1.mod
/usr/share/lv2specgen/DTD/xhtml-datatypes-1.mod.1
/usr/share/lv2specgen/DTD/xhtml-edit-1.mod
/usr/share/lv2specgen/DTD/xhtml-events-1.mod
/usr/share/lv2specgen/DTD/xhtml-form-1.mod
/usr/share/lv2specgen/DTD/xhtml-framework-1.mod
/usr/share/lv2specgen/DTD/xhtml-hypertext-1.mod
/usr/share/lv2specgen/DTD/xhtml-image-1.mod
/usr/share/lv2specgen/DTD/xhtml-inlphras-1.mod
/usr/share/lv2specgen/DTD/xhtml-inlpres-1.mod
/usr/share/lv2specgen/DTD/xhtml-inlstruct-1.mod
/usr/share/lv2specgen/DTD/xhtml-inlstyle-1.mod
/usr/share/lv2specgen/DTD/xhtml-inputmode-1.mod
/usr/share/lv2specgen/DTD/xhtml-lat1.ent
/usr/share/lv2specgen/DTD/xhtml-legacy-1.mod
/usr/share/lv2specgen/DTD/xhtml-link-1.mod
/usr/share/lv2specgen/DTD/xhtml-list-1.mod
/usr/share/lv2specgen/DTD/xhtml-meta-1.mod
/usr/share/lv2specgen/DTD/xhtml-metaAttributes-1.mod
/usr/share/lv2specgen/DTD/xhtml-object-1.mod
/usr/share/lv2specgen/DTD/xhtml-param-1.mod
/usr/share/lv2specgen/DTD/xhtml-pres-1.mod
/usr/share/lv2specgen/DTD/xhtml-qname-1.mod
/usr/share/lv2specgen/DTD/xhtml-rdfa-1.dtd
/usr/share/lv2specgen/DTD/xhtml-rdfa-model-1.mod
/usr/share/lv2specgen/DTD/xhtml-script-1.mod
/usr/share/lv2specgen/DTD/xhtml-special.ent
/usr/share/lv2specgen/DTD/xhtml-ssismap-1.mod
/usr/share/lv2specgen/DTD/xhtml-struct-1.mod
/usr/share/lv2specgen/DTD/xhtml-style-1.mod
/usr/share/lv2specgen/DTD/xhtml-symbol.ent
/usr/share/lv2specgen/DTD/xhtml-table-1.mod
/usr/share/lv2specgen/DTD/xhtml-target-1.mod
/usr/share/lv2specgen/DTD/xhtml-text-1.mod
/usr/share/lv2specgen/style.css
/usr/share/lv2specgen/template.html

%files dev
%defattr(-,root,root,-)
/usr/include/lv2.h
/usr/include/lv2/atom/atom.h
/usr/include/lv2/atom/forge.h
/usr/include/lv2/atom/util.h
/usr/include/lv2/buf-size/buf-size.h
/usr/include/lv2/core/attributes.h
/usr/include/lv2/core/lv2.h
/usr/include/lv2/core/lv2_util.h
/usr/include/lv2/data-access/data-access.h
/usr/include/lv2/dynmanifest/dynmanifest.h
/usr/include/lv2/event/event-helpers.h
/usr/include/lv2/event/event.h
/usr/include/lv2/instance-access/instance-access.h
/usr/include/lv2/log/log.h
/usr/include/lv2/log/logger.h
/usr/include/lv2/lv2plug.in/ns/ext/atom/atom.h
/usr/include/lv2/lv2plug.in/ns/ext/atom/forge.h
/usr/include/lv2/lv2plug.in/ns/ext/atom/util.h
/usr/include/lv2/lv2plug.in/ns/ext/buf-size/buf-size.h
/usr/include/lv2/lv2plug.in/ns/ext/data-access/data-access.h
/usr/include/lv2/lv2plug.in/ns/ext/dynmanifest/dynmanifest.h
/usr/include/lv2/lv2plug.in/ns/ext/event/event-helpers.h
/usr/include/lv2/lv2plug.in/ns/ext/event/event.h
/usr/include/lv2/lv2plug.in/ns/ext/instance-access/instance-access.h
/usr/include/lv2/lv2plug.in/ns/ext/log/log.h
/usr/include/lv2/lv2plug.in/ns/ext/log/logger.h
/usr/include/lv2/lv2plug.in/ns/ext/midi/midi.h
/usr/include/lv2/lv2plug.in/ns/ext/morph/morph.h
/usr/include/lv2/lv2plug.in/ns/ext/options/options.h
/usr/include/lv2/lv2plug.in/ns/ext/parameters/parameters.h
/usr/include/lv2/lv2plug.in/ns/ext/patch/patch.h
/usr/include/lv2/lv2plug.in/ns/ext/port-groups/port-groups.h
/usr/include/lv2/lv2plug.in/ns/ext/port-props/port-props.h
/usr/include/lv2/lv2plug.in/ns/ext/presets/presets.h
/usr/include/lv2/lv2plug.in/ns/ext/resize-port/resize-port.h
/usr/include/lv2/lv2plug.in/ns/ext/state/state.h
/usr/include/lv2/lv2plug.in/ns/ext/time/time.h
/usr/include/lv2/lv2plug.in/ns/ext/uri-map/uri-map.h
/usr/include/lv2/lv2plug.in/ns/ext/urid/urid.h
/usr/include/lv2/lv2plug.in/ns/ext/worker/worker.h
/usr/include/lv2/lv2plug.in/ns/extensions/ui/ui.h
/usr/include/lv2/lv2plug.in/ns/extensions/units/units.h
/usr/include/lv2/lv2plug.in/ns/lv2core/attributes.h
/usr/include/lv2/lv2plug.in/ns/lv2core/lv2.h
/usr/include/lv2/lv2plug.in/ns/lv2core/lv2_util.h
/usr/include/lv2/midi/midi.h
/usr/include/lv2/morph/morph.h
/usr/include/lv2/options/options.h
/usr/include/lv2/parameters/parameters.h
/usr/include/lv2/patch/patch.h
/usr/include/lv2/port-groups/port-groups.h
/usr/include/lv2/port-props/port-props.h
/usr/include/lv2/presets/presets.h
/usr/include/lv2/resize-port/resize-port.h
/usr/include/lv2/state/state.h
/usr/include/lv2/time/time.h
/usr/include/lv2/ui/ui.h
/usr/include/lv2/units/units.h
/usr/include/lv2/uri-map/uri-map.h
/usr/include/lv2/urid/urid.h
/usr/include/lv2/worker/worker.h
/usr/lib64/lv2/atom.lv2/atom-test-utils.c
/usr/lib64/lv2/atom.lv2/atom-test.c
/usr/lib64/lv2/atom.lv2/atom.h
/usr/lib64/lv2/atom.lv2/atom.meta.ttl
/usr/lib64/lv2/atom.lv2/atom.ttl
/usr/lib64/lv2/atom.lv2/forge-overflow-test.c
/usr/lib64/lv2/atom.lv2/forge.h
/usr/lib64/lv2/atom.lv2/manifest.ttl
/usr/lib64/lv2/atom.lv2/util.h
/usr/lib64/lv2/buf-size.lv2/buf-size.h
/usr/lib64/lv2/buf-size.lv2/buf-size.meta.ttl
/usr/lib64/lv2/buf-size.lv2/buf-size.ttl
/usr/lib64/lv2/buf-size.lv2/manifest.ttl
/usr/lib64/lv2/core.lv2/attributes.h
/usr/lib64/lv2/core.lv2/lv2.h
/usr/lib64/lv2/core.lv2/lv2_util.h
/usr/lib64/lv2/core.lv2/lv2core.meta.ttl
/usr/lib64/lv2/core.lv2/lv2core.ttl
/usr/lib64/lv2/core.lv2/manifest.ttl
/usr/lib64/lv2/core.lv2/meta.ttl
/usr/lib64/lv2/core.lv2/people.ttl
/usr/lib64/lv2/data-access.lv2/data-access.h
/usr/lib64/lv2/data-access.lv2/data-access.meta.ttl
/usr/lib64/lv2/data-access.lv2/data-access.ttl
/usr/lib64/lv2/data-access.lv2/manifest.ttl
/usr/lib64/lv2/dynmanifest.lv2/dynmanifest.h
/usr/lib64/lv2/dynmanifest.lv2/dynmanifest.meta.ttl
/usr/lib64/lv2/dynmanifest.lv2/dynmanifest.ttl
/usr/lib64/lv2/dynmanifest.lv2/manifest.ttl
/usr/lib64/lv2/eg-amp.lv2/amp.so
/usr/lib64/lv2/eg-amp.lv2/amp.ttl
/usr/lib64/lv2/eg-amp.lv2/manifest.ttl
/usr/lib64/lv2/eg-fifths.lv2/fifths.so
/usr/lib64/lv2/eg-fifths.lv2/fifths.ttl
/usr/lib64/lv2/eg-fifths.lv2/manifest.ttl
/usr/lib64/lv2/eg-metro.lv2/manifest.ttl
/usr/lib64/lv2/eg-metro.lv2/metro.so
/usr/lib64/lv2/eg-metro.lv2/metro.ttl
/usr/lib64/lv2/eg-midigate.lv2/manifest.ttl
/usr/lib64/lv2/eg-midigate.lv2/midigate.so
/usr/lib64/lv2/eg-midigate.lv2/midigate.ttl
/usr/lib64/lv2/eg-params.lv2/manifest.ttl
/usr/lib64/lv2/eg-params.lv2/params.so
/usr/lib64/lv2/eg-params.lv2/params.ttl
/usr/lib64/lv2/eg-sampler.lv2/click.wav
/usr/lib64/lv2/eg-sampler.lv2/manifest.ttl
/usr/lib64/lv2/eg-sampler.lv2/sampler.so
/usr/lib64/lv2/eg-sampler.lv2/sampler.ttl
/usr/lib64/lv2/eg-sampler.lv2/sampler_ui.so
/usr/lib64/lv2/eg-scope.lv2/examploscope.so
/usr/lib64/lv2/eg-scope.lv2/examploscope.ttl
/usr/lib64/lv2/eg-scope.lv2/examploscope_ui.so
/usr/lib64/lv2/eg-scope.lv2/manifest.ttl
/usr/lib64/lv2/event.lv2/event-helpers.h
/usr/lib64/lv2/event.lv2/event.h
/usr/lib64/lv2/event.lv2/event.meta.ttl
/usr/lib64/lv2/event.lv2/event.ttl
/usr/lib64/lv2/event.lv2/manifest.ttl
/usr/lib64/lv2/instance-access.lv2/instance-access.h
/usr/lib64/lv2/instance-access.lv2/instance-access.meta.ttl
/usr/lib64/lv2/instance-access.lv2/instance-access.ttl
/usr/lib64/lv2/instance-access.lv2/manifest.ttl
/usr/lib64/lv2/log.lv2/log.h
/usr/lib64/lv2/log.lv2/log.meta.ttl
/usr/lib64/lv2/log.lv2/log.ttl
/usr/lib64/lv2/log.lv2/logger.h
/usr/lib64/lv2/log.lv2/manifest.ttl
/usr/lib64/lv2/midi.lv2/manifest.ttl
/usr/lib64/lv2/midi.lv2/midi.h
/usr/lib64/lv2/midi.lv2/midi.meta.ttl
/usr/lib64/lv2/midi.lv2/midi.ttl
/usr/lib64/lv2/morph.lv2/manifest.ttl
/usr/lib64/lv2/morph.lv2/morph.h
/usr/lib64/lv2/morph.lv2/morph.meta.ttl
/usr/lib64/lv2/morph.lv2/morph.ttl
/usr/lib64/lv2/options.lv2/manifest.ttl
/usr/lib64/lv2/options.lv2/options.h
/usr/lib64/lv2/options.lv2/options.meta.ttl
/usr/lib64/lv2/options.lv2/options.ttl
/usr/lib64/lv2/parameters.lv2/manifest.ttl
/usr/lib64/lv2/parameters.lv2/parameters.h
/usr/lib64/lv2/parameters.lv2/parameters.meta.ttl
/usr/lib64/lv2/parameters.lv2/parameters.ttl
/usr/lib64/lv2/patch.lv2/manifest.ttl
/usr/lib64/lv2/patch.lv2/patch.h
/usr/lib64/lv2/patch.lv2/patch.meta.ttl
/usr/lib64/lv2/patch.lv2/patch.ttl
/usr/lib64/lv2/port-groups.lv2/manifest.ttl
/usr/lib64/lv2/port-groups.lv2/port-groups.h
/usr/lib64/lv2/port-groups.lv2/port-groups.meta.ttl
/usr/lib64/lv2/port-groups.lv2/port-groups.ttl
/usr/lib64/lv2/port-props.lv2/manifest.ttl
/usr/lib64/lv2/port-props.lv2/port-props.h
/usr/lib64/lv2/port-props.lv2/port-props.meta.ttl
/usr/lib64/lv2/port-props.lv2/port-props.ttl
/usr/lib64/lv2/presets.lv2/manifest.ttl
/usr/lib64/lv2/presets.lv2/presets.h
/usr/lib64/lv2/presets.lv2/presets.meta.ttl
/usr/lib64/lv2/presets.lv2/presets.ttl
/usr/lib64/lv2/resize-port.lv2/manifest.ttl
/usr/lib64/lv2/resize-port.lv2/resize-port.h
/usr/lib64/lv2/resize-port.lv2/resize-port.meta.ttl
/usr/lib64/lv2/resize-port.lv2/resize-port.ttl
/usr/lib64/lv2/schemas.lv2/dcs.ttl
/usr/lib64/lv2/schemas.lv2/dct.ttl
/usr/lib64/lv2/schemas.lv2/doap.ttl
/usr/lib64/lv2/schemas.lv2/foaf.ttl
/usr/lib64/lv2/schemas.lv2/manifest.ttl
/usr/lib64/lv2/schemas.lv2/owl.ttl
/usr/lib64/lv2/schemas.lv2/rdf.ttl
/usr/lib64/lv2/schemas.lv2/rdfs.ttl
/usr/lib64/lv2/schemas.lv2/xsd.ttl
/usr/lib64/lv2/state.lv2/manifest.ttl
/usr/lib64/lv2/state.lv2/state.h
/usr/lib64/lv2/state.lv2/state.meta.ttl
/usr/lib64/lv2/state.lv2/state.ttl
/usr/lib64/lv2/time.lv2/manifest.ttl
/usr/lib64/lv2/time.lv2/time.h
/usr/lib64/lv2/time.lv2/time.meta.ttl
/usr/lib64/lv2/time.lv2/time.ttl
/usr/lib64/lv2/ui.lv2/manifest.ttl
/usr/lib64/lv2/ui.lv2/ui.h
/usr/lib64/lv2/ui.lv2/ui.meta.ttl
/usr/lib64/lv2/ui.lv2/ui.ttl
/usr/lib64/lv2/units.lv2/manifest.ttl
/usr/lib64/lv2/units.lv2/units.h
/usr/lib64/lv2/units.lv2/units.meta.ttl
/usr/lib64/lv2/units.lv2/units.ttl
/usr/lib64/lv2/uri-map.lv2/manifest.ttl
/usr/lib64/lv2/uri-map.lv2/uri-map.h
/usr/lib64/lv2/uri-map.lv2/uri-map.meta.ttl
/usr/lib64/lv2/uri-map.lv2/uri-map.ttl
/usr/lib64/lv2/urid.lv2/manifest.ttl
/usr/lib64/lv2/urid.lv2/urid.h
/usr/lib64/lv2/urid.lv2/urid.meta.ttl
/usr/lib64/lv2/urid.lv2/urid.ttl
/usr/lib64/lv2/worker.lv2/manifest.ttl
/usr/lib64/lv2/worker.lv2/worker.h
/usr/lib64/lv2/worker.lv2/worker.meta.ttl
/usr/lib64/lv2/worker.lv2/worker.ttl
/usr/lib64/pkgconfig/lv2.pc
